title: Lattice Assumption Zoo
subtitle: Cryptographic Assumptions based on Lattices
repository: jnsiemer/latticeAssumptionZoo
logo: /assets/images/logo.svg
locale: en
description: "Lattice Assumption Zoo | Cryptographic Assumptions based on Lattices"
url: "https://latticeassumptionzoo.org"
baseurl: ""
search: true

theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "dirt"
sass:
  quiet_deps: true
  silence_deprecations:
    - import

plugins:
  - jekyll-include-cache
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-scholar
  - jekyll-feed
relative_links:
  enabled: true
  collections: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jnsiemer/latticeassumptionzoo"

collections:
  assumptions:
    output: true
    permalink: /:slug/

defaults:
  - scope:
      path: ""
      type: assumptions
    values:
      sidebar:
        nav: "main"
      layout: assumption
      toc: true
      toc_label: "On This Page"
      toc_icon: "fas fa-list"
      scholar:
        style: association-for-computing-machinery
        source: ./_bibliography
        bibliography: references.bib
        bibliography_list_tag: ul
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      sidebar:
        nav: "main"

exclude:
  - CONTRIBUTING.md
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
