services:
  laz:
    build: .
    # prevents root-owned files from being created on the host machine
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "4000:4000"
      - "35729:35729" # Port for live reload
    volumes:
      - .:/app
      # Prevents container's installed gems from being overwritten 
      # if a user has a local vendor/bundle directory
      - bundle_cache:/usr/local/bundle
    environment:
      - BUNDLE_USER_HOME=/usr/local/bundle

volumes:
  bundle_cache:
